# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Karthik Anantharamu'
tagline:          ''
description:      'Hi, if you would like to contact me, I''m available on <a href="https://plus.google.com/100897659453221053462">Google+</a>, Twitter <a href="https://twitter.com/akarthik10">Twitter</a> or <a href="https://github.com/akarthik10">GitHub</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:			  
  repo:           https://github.com/akarthik10/akarthik10.github.io
  profile:		  https://github.com/akarthik10

gems:
  - jekyll-paginate
  - jekyll-gist
