# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Karthik Anantharamu'
tagline:          ''
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Karthik A'
  url:            https://akarthik10.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:			  
  repo:           https://github.com/akarthik10/akarthik10.github.io
  profile:		  https://github.com/akarthik10

gems:
  - jekyll-paginate
  - jekyll-gist
