# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Karthik Anantharamu'
tagline:          ''
description:      'Hello, welcome here. If you would like to contact me, I am available on Github as <a href="https://github.com/akarthik10">@akarthik10</a>. You can also drop me an email at <a href="mailto:akarthik101@gmail.com">akarthik101@gmail.com</a>'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Karthik A'
  url:            https://akarthik10.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:			  
  repo:           https://github.com/akarthik10/akarthik10.github.io
  profile:		  https://github.com/akarthik10

gems:
  - jekyll-paginate
  - jekyll-gist
